version: '3'

services:
  db:
    container_name: db
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pgpassword
    ports:
      - '5432:5432'
    networks:
      - network-api
    volumes:
      - ./dados:/var/lib/postgresql/data
  web:
    container_name: web
    image: api
    depends_on:
      - db
    command: bash -c "npx sequelize db:migrate && npx sequelize db:seed:undo:all && npx sequelize db:seed:all && yarn dev"
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3333:3333'
    networks:
      - network-api
networks:
  network-api:
    external:
      name: network-api
